title: Hi! I'm Nabil
description: >
  <div style="text-align: center;">
    <img src="/images/photo_profile.jpeg?raw=true" alt="Profile Picture" 
         style="width: 210px; height: 210px; object-fit: cover; object-position: top; border-radius: 50%;">
  </div>
  <br><br>
  Full-stack data scientist with 3+ years of experience in oil & gas, education, and healthcare. 
  Certified IBM Data Science Practitioner skilled in data analysis, mining, and AI. 
  Expert in transforming raw data into actionable insights to drive decisions and business growth.
  <br><br>
  Feel free to connect with me!  
  <br><br>
  <div style="display: flex; gap: 15px; align-items: center; justify-content: flex-start; margin-top: 10px;">
  <a href="mailto:your-email@gmail.com" target="_blank" title="Email">
    <img src="https://upload.wikimedia.org/wikipedia/commons/4/4e/Gmail_Icon.png" alt="Gmail" style="width: 25px; height: 25px;"></a>
  <a href="https://medium.com/@shafandanabil" target="_blank" title="Medium">
    <img src="https://upload.wikimedia.org/wikipedia/commons/e/ec/Medium_logo_Monogram.svg" alt="Medium" style="width: 25px; height: 25px;"></a>
  <a href="https://github.com/fandanabil1379" target="_blank" title="GitHub">
    <img src="https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" alt="GitHub" style="width: 25px; height: 25px;"></a>
  <a href="https://www.linkedin.com/in/fandanabil/" target="_blank" title="LinkedIn">
    <img src="https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png" alt="LinkedIn" style="width: 25px; height: 25px;"></a>
  </div>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
